### ISSUE TITLE
Draft VR progress slide for Andy and Bob

### ISSUE THREAD

**Issue by ahwagner** [ahwagner/TRAGEDY#2]
We need to provide Andy and Bob with guidance. Short of getting them the full roadmap, at least we should give them high-level talking points.

[Here](https://docs.google.com/presentation/d/1Dwunj8jhNxmrOPZQ5Ibt7B8_IVbC5zqNJYngPru56I0/edit#slide=id.g10ca7377130_0_128) is a draft slide with some points they may cover.

**Comment by ahwagner** [comment]
Question: should we coordinate with Matt on plans for VA?

**Comment by larrybabb** [comment]
@ahwagner I've reviewed and feel the slides are sufficient for the upcoming SC status report. Ideally it would be nice to have our roadmap completed. (Maybe we should mention that in the plans - or maybe we just let that slide by?).

Anyway. I left one comment in there for you to address regarding the final point and thinking that we should accentuate/highlight VRSATILE as the spec that will provide the kind of useful implementation guidance to apply VRS and bridge that work with the VA and SA work will rely on. We may also throw in a mention that VRSATILE intends to provide use on ways to integrate VRS with VCF (something we need to not lose site of)

**Comment by ahwagner** [comment]
We do have GKS roadmap in our plans (#3), it's just not on the "ready for review" view since I'm still working on the first draft. Agreed we should get there ASAP.
